# Copyright (C) 2023 Zaitra s.r.o <info@zaitra.io>
# Zaitra s.r.o - All rights reserved.
#
# This source code is protected under international copyright law.  All rights
# reserved and protected by the copyright holders.
# This file is confidential and only available to authorized individuals with the
# permission of the copyright holders.  If you encounter this file and do not have
# permission, please contact the copyright holders and delete this file.

version: "3.7"

services:
  simple-libcsp:
    build:
      context: .
      dockerfile: Dockerfile
    image: zaitra/simple-libcsp
    container_name: simple-libcsp
    volumes:
      - ./:/home/simple-client-server
    command: "bash"